
					-- DATABASE EXPLORATION -- 
/*-- explore the data objects -- 

select * from INFORMATION_SCHEMA.TABLES

-- explore the coloumbs--

select * from INFORMATION_SCHEMA.COLUMNS

where TABLE_NAME = 'dim_customers'/

-------------------------------------------------------------------------------------------

					-- DIMENSION EXPLORATION -- 

-- EXPLORE COUNTRIES ALL CUSTOMERS FROM --

SELECT DISTINCT country FROM gold.dim_customers

	select distinct category,subcategory ,product_name from gold.dim_products
	order by 1,2,3
---------------------------------------------------------------------------------------
				
					-- DATE EXPPLORATION ---
	-- select the date from first and and last order -- 
	-- how many years of sales are available -- 
	select
	min(order_date) as first_order_date ,
	max(order_date) as last_order_date,
	datediff(year,min(order_date),max(order_date)) as order_range_years
	from gold.fact_sales

	-- find the youngest and the oldest customer-- 

	select 
	min (birthdate) as oldest_birth_date,
	datediff(YEAR,min(birthdate),getdate()) as oldest_age,
	max  (birthdate) as youngest_birthdate,
	datediff(YEAR,max(birthdate),getdate()) as youngest_age
	from gold.dim_customers
	---------------------------------------------------------------------------------------

					---- MEASURES EXPLORATION ---
	-- find the toal sales--

	select sum(sales_amount) as total_sales from gold.fact_sales

	-- how many items are sold--
	select sum(quantity) as total_quantity from gold.fact_sales
	--avg selling price--
	select avg(price) as avg_price from gold.fact_sales
	-- total number os orders--
	select count(order_number) as total_orders from gold.fact_sales
	-- total number of products --
	select count(product_key) as total_products from gold.fact_sales
	-- total numbers of customers--
	select count (customer_key) as total_customers from gold.dim_customers
	-- customers placed order -- 
	select count(distinct customer_key) as total_customer_order from gold.dim_customers

	
	
	-- generate the report that shows the metrics of buisness -- 

	select 'total sales' as measures_name ,sum (sales_amount) as measure_value from gold.fact_sales
	union all
	select 'total sales',sum(quantity) as quantity_val from gold.fact_sales
	union all 
	select 'average price', avg(price) from gold.fact_sales
	union all 
	select 'total nr.orders', count(distinct order_number) from gold.fact_sales
	union all 
	select 'total nr . products', count(product_name) from gold.dim_products
	union all 
	select 'total nr . customers', count(customer_key) from gold.dim_customers

	
	---------------------------------------------------------------------------------------

					--------magnitude analysis ---------

-- find the total customers by countries -- 
select 
country, 
count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc

-- find the customers by gender -- 
select 
gender, 
count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

-- find the total product by category

select 
category,
count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc

-- find the avg cost in each country  -- 
select 
category,
avg (cost) as avg_costs
from gold.dim_products
group by category
order by avg_costs desc 

-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
---------------------------------------------------------------------------------------

						-- ranking analysis -- 

		-- which 5 product generate the highest revenue -- 
		-- Which 5 products Generating the Highest Revenue?
-- Simple Ranking
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue;*/