                --------MAGNITUTDE ANALYSIS ---------

-- find the total customers by countries -- 
select 
country, 
count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc

-- find the customers by gender -- 
select 
gender, 
count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

-- find the total product by category

select 
category,
count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc

-- find the avg cost in each country  -- 
select 
category,
avg (cost) as avg_costs
from gold.dim_products
group by category
order by avg_costs desc 

-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;